/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Deductions {
  'professionTax' : number,
  'providentFund' : number,
}
export interface Earnings {
  'hraGrossPM' : number,
  'specialAllowanceCurrentMonth' : number,
  'statutoryBonusGrossPM' : number,
  'specialAllowanceGrossPM' : number,
  'basicGrossPM' : number,
  'mobileAllowanceCurrentMonth' : number,
  'basicArrear' : number,
  'basicCurrentMonth' : number,
  'statutoryBonusCurrentMonth' : number,
  'mobileAllowanceGrossPM' : number,
  'mobileAllowanceArrear' : number,
  'statutoryBonusArrear' : number,
  'specialAllowanceArrear' : number,
  'hraCurrentMonth' : number,
  'hraArrear' : number,
}
export interface PayPeriod { 'month' : string, 'year' : string }
export interface Payslip {
  'pan' : string,
  'uan' : string,
  'payPeriod' : PayPeriod,
  'payslipId' : bigint,
  'totalDeductions' : number,
  'employeeName' : string,
  'totalEarningsCurrentMonth' : number,
  'totalEarningsGrossPM' : number,
  'ifscCode' : string,
  'ownerId' : Principal,
  'dateOfBirth' : string,
  'arrearDays' : bigint,
  'designation' : string,
  'createdAt' : bigint,
  'deductions' : Deductions,
  'businessUnit' : string,
  'bankName' : string,
  'signDate' : string,
  'dateOfJoining' : string,
  'subFunction' : string,
  'netPayable' : number,
  'earnings' : Earnings,
  'employeeId' : string,
  'lopDays' : bigint,
  'grade' : string,
  'totalEarningsArrear' : number,
  'paymentMode' : string,
  'accountNumber' : string,
  'pfAccountNumber' : string,
  'location' : string,
  'daysPaid' : bigint,
  'amountInWords' : string,
}
export interface PayslipSummary {
  'payPeriod' : PayPeriod,
  'payslipId' : bigint,
  'employeeName' : string,
  'netPayable' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayslip' : ActorMethod<
    [
      PayPeriod,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Earnings,
      Deductions,
      number,
      number,
      number,
      number,
      number,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'deletePayslip' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPayslips' : ActorMethod<[], Array<PayslipSummary>>,
  'getPayslip' : ActorMethod<[bigint], Payslip>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePayslip' : ActorMethod<
    [
      bigint,
      PayPeriod,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Earnings,
      Deductions,
      number,
      number,
      number,
      number,
      number,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];