/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PayPeriod = IDL.Record({ 'month' : IDL.Text, 'year' : IDL.Text });
export const Attendance = IDL.Record({
  'overtimeHrs' : IDL.Text,
  'weekOff' : IDL.Nat,
  'present' : IDL.Nat,
  'weeklyOffOvertimeDays' : IDL.Nat,
  'utilisedLeave' : IDL.Nat,
  'totalDays' : IDL.Nat,
});
export const Leave = IDL.Record({
  'usedLeaves' : IDL.Nat,
  'balanceLeaves' : IDL.Nat,
  'totalAllowLeaves' : IDL.Nat,
});
export const Earnings = IDL.Record({
  'overtimeAmount' : IDL.Float64,
  'basicPay' : IDL.Float64,
  'weeklyOffOvertimeAmount' : IDL.Float64,
  'employerESI' : IDL.Float64,
});
export const Deductions = IDL.Record({
  'employeeESIDeduction' : IDL.Float64,
  'professionalTax' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PayslipSummary = IDL.Record({
  'payPeriod' : PayPeriod,
  'payslipId' : IDL.Nat,
  'netAmount' : IDL.Float64,
  'employeeName' : IDL.Text,
});
export const Payslip = IDL.Record({
  'pan' : IDL.Text,
  'uan' : IDL.Text,
  'payPeriod' : PayPeriod,
  'payslipId' : IDL.Nat,
  'netAmount' : IDL.Float64,
  'totalDeductions' : IDL.Float64,
  'signatoryName' : IDL.Text,
  'employeeName' : IDL.Text,
  'functionRole' : IDL.Text,
  'ownerId' : IDL.Principal,
  'bankDetails' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : IDL.Int,
  'pran' : IDL.Text,
  'deductions' : Deductions,
  'employersContributionEPFESIC' : IDL.Float64,
  'signDate' : IDL.Text,
  'leave' : Leave,
  'dateOfJoining' : IDL.Text,
  'earnings' : Earnings,
  'employeeNumber' : IDL.Text,
  'attendance' : Attendance,
  'totalEarnings' : IDL.Float64,
  'pfAccountNumber' : IDL.Text,
  'esiNumber' : IDL.Text,
  'location' : IDL.Text,
  'taxRegime' : IDL.Text,
  'amountInWords' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPayslip' : IDL.Func(
      [
        PayPeriod,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Attendance,
        Leave,
        Earnings,
        Deductions,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deletePayslip' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyPayslips' : IDL.Func([], [IDL.Vec(PayslipSummary)], ['query']),
  'getPayslip' : IDL.Func([IDL.Nat], [Payslip], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePayslip' : IDL.Func(
      [
        IDL.Nat,
        PayPeriod,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Attendance,
        Leave,
        Earnings,
        Deductions,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PayPeriod = IDL.Record({ 'month' : IDL.Text, 'year' : IDL.Text });
  const Attendance = IDL.Record({
    'overtimeHrs' : IDL.Text,
    'weekOff' : IDL.Nat,
    'present' : IDL.Nat,
    'weeklyOffOvertimeDays' : IDL.Nat,
    'utilisedLeave' : IDL.Nat,
    'totalDays' : IDL.Nat,
  });
  const Leave = IDL.Record({
    'usedLeaves' : IDL.Nat,
    'balanceLeaves' : IDL.Nat,
    'totalAllowLeaves' : IDL.Nat,
  });
  const Earnings = IDL.Record({
    'overtimeAmount' : IDL.Float64,
    'basicPay' : IDL.Float64,
    'weeklyOffOvertimeAmount' : IDL.Float64,
    'employerESI' : IDL.Float64,
  });
  const Deductions = IDL.Record({
    'employeeESIDeduction' : IDL.Float64,
    'professionalTax' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PayslipSummary = IDL.Record({
    'payPeriod' : PayPeriod,
    'payslipId' : IDL.Nat,
    'netAmount' : IDL.Float64,
    'employeeName' : IDL.Text,
  });
  const Payslip = IDL.Record({
    'pan' : IDL.Text,
    'uan' : IDL.Text,
    'payPeriod' : PayPeriod,
    'payslipId' : IDL.Nat,
    'netAmount' : IDL.Float64,
    'totalDeductions' : IDL.Float64,
    'signatoryName' : IDL.Text,
    'employeeName' : IDL.Text,
    'functionRole' : IDL.Text,
    'ownerId' : IDL.Principal,
    'bankDetails' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : IDL.Int,
    'pran' : IDL.Text,
    'deductions' : Deductions,
    'employersContributionEPFESIC' : IDL.Float64,
    'signDate' : IDL.Text,
    'leave' : Leave,
    'dateOfJoining' : IDL.Text,
    'earnings' : Earnings,
    'employeeNumber' : IDL.Text,
    'attendance' : Attendance,
    'totalEarnings' : IDL.Float64,
    'pfAccountNumber' : IDL.Text,
    'esiNumber' : IDL.Text,
    'location' : IDL.Text,
    'taxRegime' : IDL.Text,
    'amountInWords' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPayslip' : IDL.Func(
        [
          PayPeriod,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Attendance,
          Leave,
          Earnings,
          Deductions,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deletePayslip' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyPayslips' : IDL.Func([], [IDL.Vec(PayslipSummary)], ['query']),
    'getPayslip' : IDL.Func([IDL.Nat], [Payslip], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePayslip' : IDL.Func(
        [
          IDL.Nat,
          PayPeriod,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Attendance,
          Leave,
          Earnings,
          Deductions,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };