/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'overtimeHrs' : string,
  'weekOff' : bigint,
  'present' : bigint,
  'weeklyOffOvertimeDays' : bigint,
  'utilisedLeave' : bigint,
  'totalDays' : bigint,
}
export interface Deductions {
  'employeeESIDeduction' : number,
  'professionalTax' : number,
}
export interface Earnings {
  'overtimeAmount' : number,
  'basicPay' : number,
  'weeklyOffOvertimeAmount' : number,
  'employerESI' : number,
}
export interface Leave {
  'usedLeaves' : bigint,
  'balanceLeaves' : bigint,
  'totalAllowLeaves' : bigint,
}
export interface PayPeriod { 'month' : string, 'year' : string }
export interface Payslip {
  'pan' : string,
  'uan' : string,
  'payPeriod' : PayPeriod,
  'payslipId' : bigint,
  'netAmount' : number,
  'totalDeductions' : number,
  'signatoryName' : string,
  'employeeName' : string,
  'functionRole' : string,
  'ownerId' : Principal,
  'bankDetails' : string,
  'designation' : string,
  'createdAt' : bigint,
  'pran' : string,
  'deductions' : Deductions,
  'employersContributionEPFESIC' : number,
  'signDate' : string,
  'leave' : Leave,
  'dateOfJoining' : string,
  'earnings' : Earnings,
  'employeeNumber' : string,
  'attendance' : Attendance,
  'totalEarnings' : number,
  'pfAccountNumber' : string,
  'esiNumber' : string,
  'location' : string,
  'taxRegime' : string,
  'amountInWords' : string,
}
export interface PayslipSummary {
  'payPeriod' : PayPeriod,
  'payslipId' : bigint,
  'netAmount' : number,
  'employeeName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayslip' : ActorMethod<
    [
      PayPeriod,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Attendance,
      Leave,
      Earnings,
      Deductions,
      number,
      number,
      number,
      number,
      string,
      string,
      string,
    ],
    undefined
  >,
  'deletePayslip' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPayslips' : ActorMethod<[], Array<PayslipSummary>>,
  'getPayslip' : ActorMethod<[bigint], Payslip>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePayslip' : ActorMethod<
    [
      bigint,
      PayPeriod,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Attendance,
      Leave,
      Earnings,
      Deductions,
      number,
      number,
      number,
      number,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];